Add --enable-microsoft to configure, enable native installation kits

diff --git a/Unix/configure b/Unix/configure
--- a/Unix/configure
+++ b/Unix/configure
@@ -250,6 +250,32 @@ do
         exit 0
         ;;
 
+    --enable-microsoft)
+      enable_preexec=1
+      prefix=/opt/omi
+      localstatedir=/var/opt/omi
+      sysconfdir=/etc/opt/omi/conf
+      certsdir=/etc/opt/omi/ssl
+      enable_native_kits=1
+
+      if [ "`uname -s`" = "Linux" ]; then
+          enable_ulinux=1
+      fi
+      ;;
+
+    --enable-native-kits)
+      enable_native_kits=1
+      ;;
+
+    --enable-ulinux)
+      if [ "`uname -s`" != "Linux" ]; then
+          echo "The --enable-ulinux option is only valid on the Linux platform."
+          exit 1
+      fi
+
+      enable_ulinux=1
+      ;;
+
     *)
       echo "$0: unknown option:  $opt"
       exit 1
@@ -335,6 +361,10 @@ OPTIONS:
                             first time.
     --enable-sections       Place functions and data in sections, allowing
                             the linker to remove unused objects at link time.
+    --enable-microsoft      Enable all build options as required for Microsoft
+                            builds of OMI.
+    --enable-native-kits    Build native kits for the current operating system.
+    --enable-ulinux         Build universal SSL kits for all versions of Linux.
 
 EOF
     exit 0
@@ -347,6 +377,49 @@ fi
 ##==============================================================================
 
 buildtool="$root/buildtool"
+
+##==============================================================================
+##
+## Check if system will support ULINUX (multiple SSL version) builds
+##
+##==============================================================================
+
+if [ "$enable_ulinux" -eq 1 ]; then
+    openssl098_dir=/usr/local_ssl_0.9.8
+    openssl100_dir=/usr/local_ssl_1.0.0
+
+    case "`uname -m`" in    
+        x86_64 )
+            openssl098_libdir=${openssl098_dir}/lib
+            openssl100_libdir=${openssl100_dir}/lib64
+            ;;
+        
+        * )
+            openssl098_libdir=${openssl098_dir}/lib
+            openssl100_libdir=${openssl100_dir}/lib
+            ;;
+    esac
+
+    openssl098_cflags=`PKG_CONFIG_PATH=$openssl098_libdir/pkgconfig $pkgconfig --cflags openssl`
+    openssl098_libs=`PKG_CONFIG_PATH=$openssl098_libdir/pkgconfig $pkgconfig --libs openssl`
+    openssl100_cflags=`PKG_CONFIG_PATH=$openssl100_libdir/pkgconfig $pkgconfig --cflags openssl`
+    openssl100_libs=`PKG_CONFIG_PATH=$openssl100_libdir/pkgconfig $pkgconfig --libs openssl`
+
+
+    echo "Checking for local installation of OpenSSL version 0.9.8 on system ..."
+    if [ ! -d "$OPENSSL098_DIR" ]; then
+	echo "Did not find $(OPENSSL098_DIR), which is required."
+	echo "You must install a local copy of OpenSSL version 0.9.8 to build successfully."
+	exit 1
+    fi
+
+    echo "Checking for local installation of OpenSSL version 1.0.0 on system ..."
+    if [ ! -d "$OPENSSL100_DIR" ]; then
+	echo "Did not find $(OPENSSL100_DIR), which is required."
+	echo "You must install a local copy of OpenSSL version 1.0.0 to build successfully."
+	exit 1
+    fi
+fi
 
 ##==============================================================================
 ##
@@ -445,7 +518,6 @@ if [ -z "$namespace" ]; then
 fi
 
 if [ "$openssl" != "" ]; then
-
     if [ ! -x "$openssl" ]; then
         echo "$0: invalid option: --openssl=$openssl: no such program"
         exit 1
@@ -1402,6 +1474,8 @@ ENABLE_HTTPHEADERS=$enable_httpheaders
 ENABLE_PREEXEC=$enable_preexec
 ENABLE_SECTIONS=$enable_sections
 ENABLE_FAULTINJECTION=$enable_faultinjection
+ENABLE_NATIVE_KITS=$enable_native_kits
+ENABLE_ULINUX=$enable_ulinux
 EOF
 
 echo "created $fn"
@@ -2137,8 +2211,36 @@ export OUTPUTDIR=$outputdir
 export SYSCONFDIR=$sysconfdir
 export DATADIR=$datadir
 export ROOT=$root
+export ENABLE_ULINUX=$enable_ulinux
+
+OMI_CONFIGURE_QUALS="--microsoft"
+OPENSSL098_CFLAGS=
+OPENSSL098_LIBS=
 
 all:
+ifeq ($(ENABLE_ULINUX),1)
+
+	@echo "========================= Performing make omi (0.9.8)"
+
+	@echo Running: ./configure $(OMI_CONFIGURE_QUALS) --outputdirname=output_openssl_0.9.8 --opensslcflags="$(OPENSSL098_CFLAGS)" --openssllibs="$(OPENSSL098_LIBS)" --openssllibdir="$(OPENSSL098_LIBDIR)"; \
+	./configure $(OMI_CONFIGURE_QUALS) --outputdirname=output_openssl_0.9.8 --opensslcflags="$(OPENSSL098_CFLAGS)" --openssllibs="$(OPENSSL098_LIBS)" --openssllibdir="$(OPENSSL098_LIBDIR)"; \
+	$(MAKE) -C $(SCXOMI_DIR) all
+
+	$(ECHO) "========================= Performing make omi (1.0.0)"
+
+	export LD_LIBRARY_PATH=$(LD_LIBRARY_PATH_OPENSSL100); \
+	cd $(SCXOMI_DIR); \
+	echo Running: ./configure $(OMI_CONFIGURE_QUALS) --outputdirname=output_openssl_1.0.0 --opensslcflags="$(OPENSSL100_CFLAGS)" --openssllibs="$(OPENSSL100_LIBS)" --openssllibdir="$(OPENSSL100_LIBDIR)"; \
+	./configure $(OMI_CONFIGURE_QUALS) --outputdirname=output_openssl_1.0.0 --opensslcflags="$(OPENSSL100_CFLAGS)" --openssllibs="$(OPENSSL100_LIBS)" --openssllibdir="$(OPENSSL100_LIBDIR)"; \
+	$(MAKE) -C $(SCXOMI_DIR) all
+
+else
+
+	$(ECHO) "========================= Performing make omi"
+	$(MAKE) -C $(SCXOMI_DIR) all
+
+endif
+
 	@echo '========================= Performing Building OMI'
 	( cd \$(__ROOT); \$(MAKE) -f build.mak )
 
